"""empty message

Revision ID: 86d3ed5bb27b
Revises: e5c9797a7d0e
Create Date: 2020-04-28 14:04:15.458518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86d3ed5bb27b'
down_revision = 'e5c9797a7d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema_address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_user', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=16), nullable=True),
    sa.Column('district', sa.String(length=16), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('hallnum', sa.Integer(), nullable=True),
    sa.Column('servicecharge', sa.Float(), nullable=True),
    sa.Column('astrict', sa.Float(), nullable=True),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['c_user'], ['cinema_admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cinema_address_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema_address_model',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('c_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('district', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('score', mysql.FLOAT(), nullable=True),
    sa.Column('hallnum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('servicecharge', mysql.FLOAT(), nullable=True),
    sa.Column('astrict', mysql.FLOAT(), nullable=True),
    sa.Column('flag', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`flag` in (0,1))', name='cinema_address_model_chk_1'),
    sa.CheckConstraint('(`is_delete` in (0,1))', name='cinema_address_model_chk_2'),
    sa.ForeignKeyConstraint(['c_user'], ['cinema_admin_user.id'], name='cinema_address_model_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('cinema_address')
    # ### end Alembic commands ###
