"""empty message

Revision ID: b33fc1bcc892
Revises: a23a8673ab13
Create Date: 2020-04-28 16:38:11.575091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33fc1bcc892'
down_revision = 'a23a8673ab13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('h_address_id', sa.Integer(), nullable=True),
    sa.Column('h_num', sa.Integer(), nullable=True),
    sa.Column('h_seate', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['h_address_id'], ['cinema_address.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('h_num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hall')
    # ### end Alembic commands ###
