"""empty message

Revision ID: bdcf038ab8f2
Revises: debbe4fda790
Create Date: 2020-04-29 11:13:30.540283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdcf038ab8f2'
down_revision = 'debbe4fda790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('h_num', table_name='hall')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('h_num', 'hall', ['h_num'], unique=True)
    # ### end Alembic commands ###
