"""empty message

Revision ID: debbe4fda790
Revises: c90b05d7d6fa
Create Date: 2020-04-29 09:57:03.587375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'debbe4fda790'
down_revision = 'c90b05d7d6fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hall_movie', sa.Column('h_m_date', sa.DateTime(), nullable=True))
    op.drop_column('hall_movie', 'h_m_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hall_movie', sa.Column('h_m_data', mysql.DATETIME(), nullable=True))
    op.drop_column('hall_movie', 'h_m_date')
    # ### end Alembic commands ###
